name: Build
on:
  push:
  pull_request:

jobs:
  build-full:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build Frontend
        uses: ./.github/actions/build-frontend

      - name: Merge
        uses: ./.github/actions/build-merge

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'

      - name: Build full
        run: mvn clean package

      - name: Upload full
        uses: actions/upload-artifact@v5
        with:
          name: korrent-full
          path: target/korrent.jar

  build-lite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'

      - name: Build lite
        run: mvn clean package -Dspring-boot.repackage.skip=true

      - name: Upload lite
        uses: actions/upload-artifact@v5
        with:
          name: korrent-lite
          path: target/korrent.jar
